### ISSUE TITLE
Implement the Ruby 2.6 standard library tracking ticket

### ISSUE THREAD

**Issue by lopopolo** [artichoke/artichoke#12]
Implement the [Ruby 2.6.3 Standard Library](https://ruby-doc.org/stdlib-2.6.3/).

This ticket tracks the scheduling and completion of the [Standard Library Milestone]. Checkmarks mean a ticket to track package implementation has been created.

- [x] abbrev - GH-74
- [x] base64 - GH-75
- [x] benchmark - GH-76
- [ ] bigdecimal
- [ ] cgi
- [x] cmath
- [ ] coverage
- [ ] csv
- [ ] date
- [ ] dbm
- [ ] debug
- [x] delegate - completed artichoke/ferrocarril#110
- [ ] digest
- [ ] drb
- [ ] e2mmap
- [ ] English
- [ ] erb
- [ ] etc
- [ ] expect
- [ ] extmk
- [ ] fcntl
- [ ] fiddle
- [ ] fileutils
- [ ] find
- [x] forwardable - completed artichoke/ferrocarril#108
- [ ] gdbm
- [ ] getoptlong
- [ ] io/console
- [ ] io/nonblock
- [ ] io/wait
- [ ] ipaddr
- [ ] irb
- [ ] json - pure Ruby implementation completed artichoke/ferrocarril#126
- [ ] logger
- [ ] mathn
- [ ] matrix
- [ ] mkmf
- [ ] monitor - completed for single-threaded implementation artichoke/ferrocarril#89
- [ ] mutex_m
- [ ] net/ftp
- [ ] net/http
- [ ] net/imap
- [ ] net/pop
- [ ] net/smtp
- [ ] net/telnet
- [ ] nkf
- [ ] objspace
- [ ] observer
- [ ] open-uri
- [ ] open3
- [ ] openssl
- [ ] optparse
- [x] ostruct - completed artichoke/ferrocarril#112
- [ ] pathname
- [ ] prettyprint
- [ ] prime
- [ ] profile
- [ ] profiler
- [ ] pstore
- [ ] psych
- [ ] pty
- [ ] racc
- [ ] racc/parser
- [ ] rake
- [ ] rdoc
- [ ] readline
- [ ] resolv
- [ ] resolv-replace
- [ ] rexml
- [ ] rinda
- [ ] ripper
- [ ] rss
- [ ] rubygems
- [ ] scanf
- [ ] sdbm
- [x] securerandom - GH-34
- [x] set - completed artichoke/ferrocarril#111
- [ ] shell
- [x] shellwords
- [ ] singleton
- [ ] socket
- [ ] stringio
- [x] strscan - completed artichoke/ferrocarril#119
- [ ] sync
- [ ] syslog
- [ ] tempfile
- [ ] thwait
- [x] time - GH-33
- [ ] timeout
- [ ] tmpdir
- [ ] tracer
- [ ] tsort
- [ ] un
- [ ] unicode_normalize
- [x] uri - ~WIP in artichoke/ferrocarril#85~ - completed artichoke/ferrocarril#125
- [ ] weakref
- [ ] webrick
- [x] win32ole - GH-296
- [ ] yaml
- [x] zlib - GH-100

**Comment by lopopolo** [comment]
Old ticket:

https://ruby-doc.org/stdlib-2.6.3/

Implement the minimum subset of the stdlib required to run Rack + Sinatra. Prefer pure ruby implementations to start.

- [ ] base64
- [x] delegate - artichoke/ferrocarril#110
- [ ] digest
- [ ] erb
- [x] forwardable - artichoke/ferrocarril#108
- [x] json - artichoke/ferrocarril#126
- [x] monitor - artichoke/ferrocarril#89
- [x] ostruct - artichoke/ferrocarril#112
- [ ] securerandom - artichoke/ferrocarril#171
- [x] set - artichoke/ferrocarril#111
- [ ] stringio
- [x] strscan - artichoke/ferrocarril#119
- [ ] time - artichoke/ferrocarril#170
- [x] uri- ~WIP in artichoke/ferrocarril#85~ - artichoke/ferrocarril#125
- [ ] zlib

**Comment by johnwahba** [comment]
Chatted with @lopopolo:
I'm not sure copying and pasting the ruby classes is super sustainable. I'll try and do a codegen script for these and see how far I get.

**Comment by lopopolo** [comment]
@johnwahba this sounds great. As you import Ruby sources from [ruby/ruby](https://github.com/ruby/ruby), It might make sense to follow the pattern in the mruby-sys crate:

- one top-level `vendor` directory with a `ruby-v2_6_3` directory to contain the vendored sources
- patches located in `vendor` if necessary to get the vendored sources to parse or pass tests.

This pattern is also in use in the `spec-runner` crate for MSpec:

- copy sources to out directory in build.rs
- patch
- embed with rust-embed

I'm super excited to see if this idea pans out. It will go a long way toward spec compliance and improving the maintainability of Artichoke.

One other thing we talked about is if we are going with this approach, it makes sense to stop RuboCoping Ruby library sources.

**Comment by lopopolo** [comment]
Actually it might be easier to just vendor all of Ruby 2.6.3 and have the code gen script operate on that copy.

This would also help clean up the vendored mspec and ruby/spec checkouts in spec-runner, but I consider that out of scope for this ticket.

**Comment by lopopolo** [comment]
this ticket is outdated and not likely to be completed. stdlib packages are ported to Artichoke on an as-needed or opportunistic basis.
